apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: test-pod
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
  placement:
    clusterAffinity:
      clusterNames:
        - vm1
        - vm3
